# Generated by Django 5.0.1 on 2024-02-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_remove_menu_parent_remove_menu_url_menucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menucategory'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='main_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.menu'),
        ),
    ]
