# Generated by Django 5.0.1 on 2024-02-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_menucategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.menucategory'),
        ),
    ]
